name: kaku
version: 1.9.0
summary: Kaku is a highly integrated music player supports different online platforms. 
description: |
  Kaku is a highly integrated music player supports
  different online platform like YouTube, SoundCloud,
  Vimeo and more.

grade: stable
confinement: classic

parts:
  kaku:
    plugin: dump
    source: https://github.com/EragonJ/Kaku/releases/download/$SNAPCRAFT_PROJECT_VERSION/Kaku-$SNAPCRAFT_PROJECT_VERSION-amd64.deb
    source-type: deb
    # Correct path to icon.
    prepare: |
      sed -i 's|Icon=kaku|Icon=/usr/share/kaku/logo\.png|g' usr/share/applications/kaku.desktop
    after:
      - desktop-gtk2
    stage-packages:
      - gconf-service
      - libasound2
      - libatk1.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libexpat1
      - libfontconfig1
      - libfreetype6
      - libgcc1
      - libgconf-2-4
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgtk2.0-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libstdc++6
      - libx11-6
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
  electron-launch:
    plugin: dump
    source: files/

apps:
  kaku:
    command: bin/electron-launch classic ${SNAP}/usr/share/kaku/kaku
    desktop: usr/share/applications/kaku.desktop